# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59ab075c40844e902c994bfb23437118fe791c5b37b6f922be595ffd6b510ea7f585a236173a3b86a67b5da838d1160cef1e8677f319e45e7a194920dade1d11

test:
  secret_key_base: 069f9305da09d22bae00ff558b8473b0b2dccca4dce546f485531978582fc1fa685cb475735457d56c97d953902dbb02b2dfe66d5b34b6fb8a83ea1f6a87bd6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
